### ISSUE TITLE
the script doesn't get past posts and shows error

### ISSUE THREAD

**Issue by AriaShishegaran** [timgrossmann/instagram-profilecrawl#14]
```
root@ubuntu:/home/aria/instagram-profilecrawl# python3.5 crawl_profile.py sabaasafari
Extracting information from sabaasafari
BEFORE IMG
- Could not get information from post: https://www.instagram.com/p/BWc05WaHn8u/?taken-by=sabaasafari
BEFORE IMG
	- Could not get information from post: https://www.instagram.com/p/BWYS2inHYsN/?taken-by=sabaasafari
BEFORE IMG
- Could not get information from post: https://www.instagram.com/p/BWUkEu5HAEe/?taken-by=sabaasafari
BEFORE IMG
- Could not get information from post: https://www.instagram.com/p/BWTDPuxnG79/?taken-by=sabaasafari

```

can you test this and see if this happens on ur side as well or not? if yes can you provide a fix?

**Comment by AriaShishegaran** [comment]
selenium also has the problem where it only scrolls one time and then starts opening posts and then it gets stuck on the first post, then it goes to 2nd, 3rd, 4th.....
nothing usable so far

**Comment by tcvieira** [comment]
This is happening because of the `load more comments` link that load others comment by demand.

At line 68 of extractor.py we have `tags = comments[0].text + ' ' + comments[1].text`, I think it's this way because most people put their tags in the post caption (first comment) and then a bunch of other tags on the second comment. 

Because ` comments[1].text` it's a link we get a error.

I'll submit a pull request that fixes this problem by clicking on `load more comments` until all comments are loaded like the script do to load all post of the profile.

**Comment by timgrossmann** [comment]
#15
