### ISSUE TITLE
[Feature Request] - adding an option to only receive the public data of each profile instead of crawling it to the end

### ISSUE THREAD

**Issue by AriaShishegaran** [timgrossmann/instagram-profilecrawl#17]
It would be great if you add an option so that user can only retrieve Username, # of Posts, # of Followers, # of Following, and Bio. it is very efficient for big crawls when you only need to identify a certain group of people in contrast to dumping their whole profile data.

**Comment by tcvieira** [comment]
@AriaShishegaran, I came up with an adjustment on the script that does exactly that and still extract the number of likes and comments much faster. The only down side is that it's not possible to retrieve the tags as I do not get into each post page.

You can comment the loop on the script that passes through the posts links so that you'll get what you want except for the profile bio.

**Comment by AriaShishegaran** [comment]
Lemme do that and get back to you. meantime, can this be done for the bio as well as a later fix?

**Comment by AriaShishegaran** [comment]
you mean this part?
```
for link in links:
    browser.get(link)

    try:
      img, tags, likes, comments = extract_post_info(browser)

      post_infos.append({
        'img': img,
        'tags': tags,
        'likes': likes,
        'comments': comments
      })
    except NoSuchElementException:
      print('- Could not get information from post: ' + link)

  information = {
    'alias': alias_name,
    'username': username,
    'prof_img': prof_img,
    'num_of_posts': num_of_posts,
    'followers': followers,
    'following': following,
    'posts': post_infos
  }

  
  return information
```
