### ISSUE TITLE
[Feature Request] - Get a list of the most engaged followers ordered by rank

### ISSUE THREAD

**Issue by samu91gn** [timgrossmann/instagram-profilecrawl#77]
It would be nice to get some info about who left the likes and not just the number so that it would be easy to understand which followers are more active and interacting more with the posts. Is this even possible without a login? Thanks!

**Comment by timmoh** [comment]
seems to be not public.
you just get the users who commented a post, but don't get everyone who liked the image.
just test it by your self: use private mode on browser and test where to we can get the likes of the pictures/posts

Perhaps Instapy would help

**Comment by samu91gn** [comment]
Alright, thanks, I will close this since it seems not possible / out of scope.

**Comment by justdvl** [comment]
It's not difficult to do. I Did the commenters module, when you get a list
of users who commented on that profile photos sorted by frequency..
To do same with likes is easy. All you need is to login..
And I can do that too. Question is if we want to incorporate login
functionality into this lightweight scrip.

On Jul 12, 2018 5:44 PM, "Samuele Illuminati" <notifications@github.com>
wrote:

Alright, thanks, I will close this since it seems not possible / out of
scope.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/timgrossmann/instagram-profilecrawl/issues/77#issuecomment-404557743>,
or mute the thread
